name: Deploy to WordPress.org

on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    name: Deploy Plugin to WordPress.org SVN
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to WordPress.org Plugin SVN
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: wpdevs-classic-editor-widgets
